### ISSUE TITLE
Create forecast parameters selection page 

### ISSUE THREAD

**Issue by lenok3383** [lenok3383/WeatherService#1]
• Create template
• Create view
• Create moduls (2) for getting forecast from services

**Comment by monsert** [comment]
**page will include**
- Input field. User will have possibility to type city
- Checkboxes with name of services
- dropdown - "today", "tomorrow", "next Sunday"
- submit button

**Comment by lenok3383** [comment]
please use classes instead of functions in moduls for getting forecast from services
it can be one class with all of functions for getting forecast in it
